# Generated by Django 5.1.1 on 2025-02-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvpdf', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
